from typing import Any

from common.llm import ask_llm_json


def _slug(value: str) -> str:
    return "".join(char.lower() if char.isalnum() else "-" for char in value).strip("-")


def provision_repository_payload(payload: dict[str, Any]) -> dict[str, Any]:
    spec = payload["spec"]
    repo_name = _slug(f"{spec['name']}-{spec['environment']}-infra")
    title = spec["name"]
    environment = spec["environment"]
    workload = spec["workload_type"]
    terraform_files = _generate_terraform_with_llm(spec) or _generate_terraform(spec)
    reference_files = _generate_reference_library(spec)
    return {
        "message": "The Provisioner Agent generated Terraform source and documentation.",
        "data": {
            "repo_name": repo_name,
            "private": spec.get("github_visibility", "private") != "public",
            "generation_mode": "agent_generated",
            "files": {
                "README.md": (
                    f"# {title} Infrastructure\n\n"
                    "Generated by the Provisioner Agent in AgentCore Multi-Agent Deployer.\n\n"
                    "## What This Project Does\n\n"
                    f"- Workload type: `{workload}`\n"
                    f"- Environment: `{environment}`\n"
                    f"- Region: `{spec['region']}`\n"
                    "- Creates Terraform infrastructure generated specifically for this request.\n"
                    "- Stores project state and logs in the platform S3 state bucket.\n"
                    "- Runs compliance checks before approval and deployment.\n\n"
                    "## End-To-End Flow\n\n"
                    "1. Chatbot gathers requirements and customization details.\n"
                    "2. Provisioner Agent generates Terraform and docs from the request context.\n"
                    "3. Orchestrator validates the generated Terraform before any GitHub push.\n"
                    "4. User approves deployment in chat.\n"
                    "5. Deployment agent applies the approved project workflow.\n"
                ),
                "ARCHITECTURE.md": (
                    f"# {title} Architecture\n\n"
                    f"Environment: `{environment}`\n\n"
                    "## Components\n\n"
                    "- AgentCore requirement, provisioner, compliance, and deployer runtimes.\n"
                    "- FastAPI orchestrator coordinating project state and approvals.\n"
                    "- GitHub repository containing Terraform and generated documentation.\n"
                    "- S3 project archive for state snapshots and execution logs.\n"
                    "- AWS workload resources generated by the Provisioner Agent under `terraform/`.\n\n"
                    "## Security Baseline\n\n"
                    "The generated infrastructure follows the company baseline: encryption, required "
                    "tags, least-privilege defaults where practical, and CloudWatch/SSM access where applicable.\n"
                ),
                "OPERATIONS.md": (
                    "# Operations\n\n"
                    "Use the orchestrator UI chatbot to gather requirements, review the generated "
                    "architecture, approve deployment, monitor logs, and destroy tracked resources.\n\n"
                    "## GitHub Read/Write\n\n"
                    "The provisioner can create this repository, update files, and read committed "
                    "content back for verification when a GitHub token is configured.\n"
                ),
                "COMPLIANCE.md": (
                    "# Compliance\n\n"
                    "Compliance checks are run before deployment. High and critical findings block deployment.\n"
                ),
                "terraform/README.md": (
                    "Run `terraform init`, `terraform plan`, and `terraform apply` through the approved pipeline.\n"
                ),
                **{f"terraform/{path}": content for path, content in terraform_files.items()},
            },
            "reference_files": reference_files,
            "customization_questions": [],
        },
    }


def _generate_terraform(spec: dict[str, Any]) -> dict[str, str]:
    workload = spec["workload_type"]
    if workload == "ec2-httpd":
        return _ec2_httpd_project_terraform(spec)
    if workload == "s3-bucket":
        return _s3_bucket_project_terraform(spec)
    return _s3_lambda_api_project_terraform(spec)


def _generate_terraform_with_llm(spec: dict[str, Any]) -> dict[str, str] | None:
    result = ask_llm_json(
        "You are a senior AWS Terraform engineer. Return only JSON with Terraform file contents.",
        (
            "Generate secure Terraform for this AWS infrastructure request. "
            "Return JSON shaped as {\"files\":{\"versions.tf\":\"...\",\"variables.tf\":\"...\","
            "\"backend.tf\":\"...\",\"main.tf\":\"...\"}}. Use the S3 backend bucket "
            "hack-aib-tf-backend. Do not include secrets or private keys. For EC2, prefer SSM Session "
            "Manager and include aws_instance. For S3, include public access block, versioning, and encryption. "
            "If requirements are incomplete, infer secure defaults using AWS Well-Architected practices. "
            "Prefer reusable official/community Terraform module patterns where applicable. "
            f"Request spec: {spec}"
        ),
    )
    files = result.get("files") if result else None
    if not isinstance(files, dict):
        return None
    expected = {"versions.tf", "variables.tf", "backend.tf", "main.tf"}
    if not expected.issubset(files):
        return None
    normalized = {str(path): str(content) for path, content in files.items() if path in expected}
    main_tf = normalized.get("main.tf", "")
    backend_tf = normalized.get("backend.tf", "")

    # Basic safety checks for common invalid LLM patterns.
    if backend_tf.count("{") != backend_tf.count("}"):
        return None
    if "backend \"s3\"" not in backend_tf:
        return None
    if "hack-aib-tf-backend" not in backend_tf:
        return None
    if "var." in backend_tf:
        return None
    if "dynamodb_table" in backend_tf:
        return None
    if main_tf.count("{") != main_tf.count("}"):
        return None
    if "public_access_block_configuration" in main_tf:
        return None

    # Reject LLM output if workload-defining markers are missing; fallback will use deterministic generator.
    marker_map = {
        "ec2-httpd": "aws_instance",
        "s3-bucket": "aws_s3_bucket",
        "s3-lambda-api": "aws_lambda_function",
        "vpc-baseline": "aws_vpc",
    }
    marker = marker_map.get(str(spec.get("workload_type", "")))
    if marker and marker not in main_tf:
        return None

    if str(spec.get("workload_type")) == "s3-bucket":
        required_s3_resources = (
            "aws_s3_bucket_public_access_block",
            "aws_s3_bucket_versioning",
            "aws_s3_bucket_server_side_encryption_configuration",
        )
        if not all(resource in main_tf for resource in required_s3_resources):
            return None
    return normalized


def _common_versions_tf() -> str:
    return """terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}
"""


def _common_provider_tf(spec: dict[str, Any]) -> str:
    return f"""provider "aws" {{
  region = var.region

  default_tags {{
    tags = {{
      Environment = var.environment
      Owner       = var.owner
      CostCenter  = var.cost_center
      ManagedBy   = "agentcore-multi-agent-deployer"
      Project     = var.name
    }}
  }}
}}

variable "name" {{
  type    = string
  default = "{_slug(spec['name'])}"
}}

variable "region" {{
  type    = string
  default = "{spec['region']}"
}}

variable "environment" {{
  type    = string
  default = "{spec['environment']}"
}}

variable "owner" {{
  type    = string
  default = "{spec['owner']}"
}}

variable "cost_center" {{
  type    = string
  default = "{spec['cost_center']}"
}}
"""


def _backend_tf(spec: dict[str, Any]) -> str:
    return f"""terraform {{
  backend "s3" {{
    bucket = "hack-aib-tf-backend"
    key    = "{_slug(spec['name'])}/{spec['environment']}/terraform.tfstate"
    region = "{spec['region']}"
  }}
}}
"""


def _ec2_httpd_project_terraform(spec: dict[str, Any]) -> dict[str, str]:
    name = _slug(spec["name"])
    instance_type = spec.get("tags", {}).get("InstanceType", "t3.micro")
    main_tf = f"""data "aws_ami" "amazon_linux" {{
  most_recent = true
  owners      = ["amazon"]

  filter {{
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }}
}}

data "aws_vpc" "default" {{
  default = true
}}

data "aws_subnets" "default" {{
  filter {{
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }}
}}

resource "aws_iam_role" "ssm" {{
  name = "{name}-${{var.environment}}-ec2-ssm"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {{
        Service = "ec2.amazonaws.com"
      }}
    }}]
  }})
}}

resource "aws_iam_role_policy_attachment" "ssm" {{
  role       = aws_iam_role.ssm.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}}

resource "aws_iam_instance_profile" "ssm" {{
  name = "{name}-${{var.environment}}-ec2-profile"
  role = aws_iam_role.ssm.name
}}

resource "aws_security_group" "httpd" {{
  name        = "{name}-${{var.environment}}-httpd"
  description = "Allow HTTP access to the generated EC2 HTTPD instance"
  vpc_id      = data.aws_vpc.default.id

  ingress {{
    description = "HTTP"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  egress {{
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}
}}

resource "aws_instance" "httpd" {{
  ami                         = data.aws_ami.amazon_linux.id
  instance_type               = "{instance_type}"
  subnet_id                   = data.aws_subnets.default.ids[0]
  vpc_security_group_ids      = [aws_security_group.httpd.id]
  iam_instance_profile        = aws_iam_instance_profile.ssm.name
  associate_public_ip_address = true

  user_data = <<-USERDATA
    #!/bin/bash
    set -eux
    dnf install -y httpd
    systemctl enable --now httpd
    echo "Hello from {name} ${{var.environment}}" > /var/www/html/index.html
  USERDATA

  tags = {{
    Name = "{name}-${{var.environment}}-httpd"
  }}
}}

output "http_url" {{
  value = "http://${{aws_instance.httpd.public_ip}}"
}}

output "access_method" {{
  value = "Use AWS Systems Manager Session Manager. No private SSH key is committed to GitHub."
}}
"""
    return {
        "versions.tf": _common_versions_tf(),
        "variables.tf": _common_provider_tf(spec),
        "backend.tf": _backend_tf(spec),
        "main.tf": main_tf,
    }


def _s3_bucket_project_terraform(spec: dict[str, Any]) -> dict[str, str]:
    name = _slug(spec["name"])
    main_tf = f"""data "aws_caller_identity" "current" {{}}

resource "aws_s3_bucket" "project" {{
  bucket = "{name}-${{var.environment}}-${{data.aws_caller_identity.current.account_id}}-agentcore"
}}

resource "aws_s3_bucket_public_access_block" "project" {{
  bucket                  = aws_s3_bucket.project.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

resource "aws_s3_bucket_versioning" "project" {{
  bucket = aws_s3_bucket.project.id

  versioning_configuration {{
    status = "Enabled"
  }}
}}

resource "aws_s3_bucket_server_side_encryption_configuration" "project" {{
  bucket = aws_s3_bucket.project.id

  rule {{
    apply_server_side_encryption_by_default {{
      sse_algorithm = "AES256"
    }}
  }}
}}

output "bucket_name" {{
  value = aws_s3_bucket.project.bucket
}}
"""
    return {
        "versions.tf": _common_versions_tf(),
        "variables.tf": _common_provider_tf(spec),
        "backend.tf": _backend_tf(spec),
        "main.tf": main_tf,
    }


def _s3_lambda_api_project_terraform(spec: dict[str, Any]) -> dict[str, str]:
    name = _slug(spec["name"])
    main_tf = f"""resource "aws_s3_bucket" "artifacts" {{
  bucket_prefix = "{name}-${{var.environment}}-artifacts-"
}}

resource "aws_iam_role" "lambda" {{
  name = "{name}-${{var.environment}}-lambda"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {{
        Service = "lambda.amazonaws.com"
      }}
    }}]
  }})
}}

resource "aws_iam_role_policy_attachment" "lambda_logs" {{
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}}

data "archive_file" "handler" {{
  type        = "zip"
  output_path = "${{path.module}}/handler.zip"

  source {{
    content  = "def handler(event, context):\\n    return {{'statusCode': 200, 'body': 'ok'}}\\n"
    filename = "handler.py"
  }}
}}

resource "aws_lambda_function" "api" {{
  function_name    = "{name}-${{var.environment}}"
  role             = aws_iam_role.lambda.arn
  handler          = "handler.handler"
  runtime          = "python3.11"
  filename         = data.archive_file.handler.output_path
  source_code_hash = data.archive_file.handler.output_base64sha256
}}
"""
    return {
        "versions.tf": _common_versions_tf().replace(
            "    }\n  }\n}",
            """    }
    archive = {
      source  = "hashicorp/archive"
      version = ">= 2.4"
    }
  }
}""",
        ),
        "variables.tf": _common_provider_tf(spec),
        "backend.tf": _backend_tf(spec),
        "main.tf": main_tf,
    }


def _generate_reference_library(spec: dict[str, Any]) -> dict[str, str]:
    generic = {
        **spec,
        "name": "example-workload",
        "region": "us-east-1",
        "environment": "dev",
        "owner": "platform-team",
        "cost_center": "CC0000",
    }
    terraform_files = _generate_terraform(generic)
    workload = spec["workload_type"]
    return {
        f"patterns/{workload}/README.md": (
            f"# {workload} Terraform Pattern\n\n"
            "Reusable reference generated by the Provisioner Agent. This pattern intentionally "
            "uses generic values and Terraform variables so it can guide future generations "
            "without carrying project-specific user input.\n"
        ),
        **{f"patterns/{workload}/{path}": content for path, content in terraform_files.items()},
    }
