from pathlib import Path
from string import Template
from typing import Any


def _slug(value: str) -> str:
    return "".join(char.lower() if char.isalnum() else "-" for char in value).strip("-")


def render_terraform(spec: dict[str, Any], template_root: Path) -> dict[str, str]:
    variables = {
        "name": _slug(spec["name"]),
        "region": spec["region"],
        "environment": spec["environment"],
        "owner": spec["owner"],
        "cost_center": spec["cost_center"],
    }
    rendered: dict[str, str] = {}
    for path in template_root.glob("*.tf.tmpl"):
        rendered[path.name.removesuffix(".tmpl")] = Template(path.read_text()).safe_substitute(variables)
    return rendered


def provision_repository_payload(payload: dict[str, Any]) -> dict[str, Any]:
    spec = payload["spec"]
    repo_name = _slug(f"{spec['name']}-{spec['environment']}-infra")
    title = spec["name"]
    environment = spec["environment"]
    return {
        "message": "Terraform source is ready to commit to GitHub.",
        "data": {
            "repo_name": repo_name,
            "private": spec.get("github_visibility", "private") != "public",
            "files": {
                "README.md": (
                    f"# {title} Infrastructure\n\n"
                    "Generated by AgentCore Multi-Agent Deployer.\n\n"
                    "## How To Use\n\n"
                    "1. Review `terraform/`.\n"
                    "2. Run compliance checks.\n"
                    "3. Deploy only through the approved pipeline.\n"
                ),
                "ARCHITECTURE.md": (
                    f"# {title} Architecture\n\n"
                    f"Environment: `{environment}`\n\n"
                    "The generated infrastructure follows the company baseline: encrypted Terraform "
                    "state, required tags, KMS encryption, S3 public access block, and CloudWatch logs.\n"
                ),
                "OPERATIONS.md": (
                    "# Operations\n\n"
                    "Use the orchestrator UI to run plan, compliance, approval, deployment, "
                    "remediation, and documentation updates.\n"
                ),
                "COMPLIANCE.md": (
                    "# Compliance\n\n"
                    "Compliance checks are run before deployment. High and critical findings block deployment.\n"
                ),
                "terraform/README.md": (
                    "Run `terraform init`, `terraform plan`, and `terraform apply` through the approved pipeline.\n"
                ),
            },
            "customization_questions": [
                {
                    "id": "approval_branch",
                    "label": "Which branch should receive deployment approvals?",
                    "default_value": "main",
                    "required": True,
                },
                {
                    "id": "notification_channel",
                    "label": "Where should deployment notifications be sent?",
                    "default_value": "email",
                    "required": False,
                },
            ],
        },
    }
