from pathlib import Path
from string import Template
from typing import Any


def _slug(value: str) -> str:
    return "".join(char.lower() if char.isalnum() else "-" for char in value).strip("-")


def render_terraform(spec: dict[str, Any], template_root: Path) -> dict[str, str]:
    variables = {
        "name": _slug(spec["name"]),
        "region": spec["region"],
        "environment": spec["environment"],
        "owner": spec["owner"],
        "cost_center": spec["cost_center"],
    }
    rendered: dict[str, str] = {}
    for path in template_root.glob("*.tf.tmpl"):
        rendered[path.name.removesuffix(".tmpl")] = Template(path.read_text()).safe_substitute(variables)
    return rendered


def provision_repository_payload(payload: dict[str, Any]) -> dict[str, Any]:
    spec = payload["spec"]
    repo_name = _slug(f"{spec['name']}-{spec['environment']}-infra")
    title = spec["name"]
    environment = spec["environment"]
    workload = spec["workload_type"]
    return {
        "message": "Terraform source is ready to commit to GitHub.",
        "data": {
            "repo_name": repo_name,
            "private": spec.get("github_visibility", "private") != "public",
            "files": {
                "README.md": (
                    f"# {title} Infrastructure\n\n"
                    "Generated by AgentCore Multi-Agent Deployer.\n\n"
                    "## What This Project Does\n\n"
                    f"- Workload type: `{workload}`\n"
                    f"- Environment: `{environment}`\n"
                    f"- Region: `{spec['region']}`\n"
                    "- Creates Terraform infrastructure with secure defaults.\n"
                    "- Stores project state and logs in the platform S3 state bucket.\n"
                    "- Runs compliance checks before approval and deployment.\n\n"
                    "## End-To-End Flow\n\n"
                    "1. Chatbot gathers requirements and customization details.\n"
                    "2. Provisioner creates this GitHub repository and commits Terraform/docs.\n"
                    "3. Compliance agent checks the generated infrastructure.\n"
                    "4. User approves deployment in chat.\n"
                    "5. Deployment agent applies the approved project workflow.\n"
                ),
                "ARCHITECTURE.md": (
                    f"# {title} Architecture\n\n"
                    f"Environment: `{environment}`\n\n"
                    "## Components\n\n"
                    "- AgentCore requirement, provisioner, compliance, and deployer runtimes.\n"
                    "- FastAPI orchestrator coordinating project state and approvals.\n"
                    "- GitHub repository containing Terraform and generated documentation.\n"
                    "- S3 project archive for state snapshots and execution logs.\n"
                    "- AWS workload resources generated from `terraform/`.\n\n"
                    "## Security Baseline\n\n"
                    "The generated infrastructure follows the company baseline: encryption, required "
                    "tags, S3 public access block, versioning where applicable, and CloudWatch logs.\n"
                ),
                "OPERATIONS.md": (
                    "# Operations\n\n"
                    "Use the orchestrator UI chatbot to gather requirements, review the generated "
                    "architecture, approve deployment, monitor logs, and destroy tracked resources.\n\n"
                    "## GitHub Read/Write\n\n"
                    "The provisioner can create this repository, update files, and read committed "
                    "content back for verification when a GitHub token is configured.\n"
                ),
                "COMPLIANCE.md": (
                    "# Compliance\n\n"
                    "Compliance checks are run before deployment. High and critical findings block deployment.\n"
                ),
                "terraform/README.md": (
                    "Run `terraform init`, `terraform plan`, and `terraform apply` through the approved pipeline.\n"
                ),
            },
            "customization_questions": [],
        },
    }
